# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=3
RESTRICT_PYTHON_ABIS="3.*"

inherit distutils


DESCRIPTION="comprehensive password hashing framework supporting over 20 schemes"
HOMEPAGE="http://code.google.com/p/passlib/"
SRC_URI="http://pypi.python.org/packages/source/p/passlib/${P}.tar.gz"
LICENSE="BSD-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE="test doc"
DEPEND="dev-python/setuptools
	test? ( dev-python/nose )"


src_install() {
	distutils_src_install
	if use doc; then
		dodoc "${S}"/docs/*
	fi

}

src_test() {
	PYTHONPATH=. "${python}" setup.py nosetests || die "tests failed"
}

